"""Interfaces - Protocol definitions for dependency injection.

Sử dụng Python Protocol (structural subtyping) để định nghĩa interfaces
mà không cần kế thừa.
"""
from typing import Any, Callable, Optional, Protocol


class IAudioService(Protocol):
    """Interface cho audio service."""
    
    @property
    def is_speaking(self) -> bool: ...
    
    def speak(self, text: str, update_ui: bool = True) -> Any: ...
    def listen(self) -> Optional[str]: ...
    def wait_until_speaking_done(self) -> None: ...
    def stop_speaking(self) -> None: ...


class ISqlService(Protocol):
    """Interface cho SQL service."""
    
    def start_session(self, user_name: str) -> Optional[int]: ...
    def end_session(self, session_id: Optional[int] = None) -> None: ...
    def save_conversation(self, user_name: str, user_msg: str, 
                          bot_response: str, session_id: Optional[int] = None) -> None: ...
    def get_session_conversations(self, session_id: int) -> list: ...


class IActionHandler(Protocol):
    """Interface cho action handler."""
    
    def handle(self, intent: str, text: str, user_name: str) -> str: ...
    def set_user_name(self, name: str) -> None: ...


class IUserController(Protocol):
    """Interface cho user controller/service (merged)."""
    
    login_name: str
    display_name: str
    
    def get_display_name(self) -> str: ...
    def get_login_name(self) -> str: ...
    def get_display_name_by_login(self, login_name: str) -> str: ...
    def update_user_name(self, new_name: str) -> tuple: ...
    def set_login_username(self, username: str) -> None: ...
    def is_name_known(self) -> bool: ...


class IAlertManager(Protocol):
    """Interface cho alert manager."""
    
    def start_monitoring(self) -> None: ...
    def stop_monitoring(self) -> None: ...
    def set_sleep_mode(self, enabled: bool) -> None: ...
    def reset_wellness_timers(self) -> None: ...


class IAnalyticsService(Protocol):
    """Interface cho analytics service."""
    
    def start(self) -> None: ...
    def stop(self) -> None: ...


class IVoiceController(Protocol):
    """Interface cho voice controller/service."""
    
    @property
    def is_sleeping(self) -> bool: ...
    @property
    def is_speaking(self) -> bool: ...
    
    def get_voice_input(self) -> Optional[str]: ...
    def speak(self, text: str, update_ui: bool = True) -> Any: ...
    def wait_until_speaking_done(self) -> None: ...
    def start_wake_word_detection(self, wake_up_callback: Callable, 
                                   on_wake_word_callback: Optional[Callable] = None) -> None: ...
    def stop_wake_word_detection(self) -> None: ...
    def handle_wake_up(self) -> None: ...
    def go_to_sleep(self, manual: bool, speak_callback: Callable) -> None: ...
    def start_idle_monitor(self, on_idle_timeout: Callable) -> None: ...
    def stop_idle_monitor(self) -> None: ...
    def cleanup(self) -> None: ...


class IUserService(Protocol):
    """Interface cho user service."""
    
    login_name: str
    display_name: str
    
    def get_user_name(self) -> str: ...
    def get_display_name_by_login(self, login_name: str) -> str: ...
    def update_user_name(self, new_name: str) -> tuple: ...


class IMemoryService(Protocol):
    """Interface cho memory service."""
    
    def save_exchange(self, user_name: str, user_msg: str,
                      bot_response: str, session_id: Optional[int] = None) -> None: ...
    def get_session_history(self, session_id: int) -> list: ...


class IIntentService(Protocol):
    """Interface cho intent service."""
    
    def classify(self, text: str) -> str: ...
    def extract_name(self, text: str) -> Optional[str]: ...


class IConversationService(Protocol):
    """Interface cho conversation service."""
    
    def init_memory_service(self, memory_service: IMemoryService) -> None: ...
    def process_exchange(self, user_input: str,
                         speak_callback: Optional[Callable],
                         user_name: str) -> str: ...
    def should_exit(self, user_input: str) -> bool: ...
